Create Fragments
Leo9Rdo/FinancialWallet pull request #1
Opened 2024-07-06 14:21 UTC by Leo9Rdo

Create Fragments: 
- HomeFragment
- SettingsFragment
- PortfolioFragment
- AssetListFragments

2024-07-07 18:19 UTC, AndrewRav requested changes

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/MainActivity.kt
Наверное лучше убрать лишний код, который генерирует Андроид Студио по дефолту

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/PortfolioListFragment.kt
Убрать лишние комменты в коде, заменить `ARG_PARAM` и `param` на осмысленные переменные. Использовать биндинг. Константы перекинуть в companion object

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/SettingsFragment.kt
Здесь тоже комменты убрать. Также заменить `ARG_PARAM` и `param` на осмысленные переменные. Использовать биндинг. Константы перекинуть в companion object

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/AssetListFragment.kt
Мне кажется, лучше использовать осмысленные переменные вместо `ARG_PARAM` и `param`. Например, здесь я бы использовал `ARG_ASSET_TYPE = "asset_type"` и `ARG_FILTER = "filter"` и соответственно `assetType` и `filter` вместо `param1 `и `param2`. Также надо бы использовать биндинг вместо инфлейтера. И если уже юзаем companion object, то давай везде в нём хранить константы

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/HomeFragment.kt
Заменить `ARG_PARAM` осмысленные переменные

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/res/values/strings.xml
Это что и зачем нам сейчас?

2024-07-07 18:19 UTC, AndrewRav commented on app/src/main/res/values/arrays.xml
Это что и зачем нам сейчас?

2024-07-09 14:42 UTC, AndrewRav commented
Это был первый и последний ПР, где мы вдвоём вносили существенные изменения. Дальше один ПР - один человек вносит изменения. Также, решили, что навигацию с помощью Navigation Component выделим в отдельную задачу с отдельным ПР, вне этого.

2024-07-09 18:59 UTC, Leo9Rdo commented
Всё гуд

2024-07-09 19:04 UTC, pzinkevich42innowise commented
> Также, решили, что навигацию с помощью Navigation Component выделим в отдельную задачу с отдельным ПР, вне этого.
нуок

2024-07-09 19:08 UTC, pzinkevich42innowise requested changes

2024-07-09 19:08 UTC, pzinkevich42innowise commented on app/build.gradle
> +    implementation libs.androidx.preference.ktx
опа, лишнее пролезло

2024-07-09 19:08 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Ну может Constraint не нужен уже?

2024-07-09 19:08 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:id="@+id/textView"
го как-то переназовём

2024-07-09 19:08 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
> +        android:layout_width="match_parent"
```suggestion
        android:layout_width="0dp"
```

2024-07-09 19:08 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
Ну да, не нужны изменения эти

2024-07-09 20:13 UTC, pzinkevich42innowise requested changes

2024-07-09 20:13 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
А лайнир тут что делает?

2024-07-09 20:57 UTC, pzinkevich42innowise requested changes

2024-07-09 20:57 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Какую роль Frame layout тут играет?

Почему нельзя оставить только один? Зачем одну ViewGroup оборачивать в другую? 

Ну сколько раз можно писать одно и то же???

2024-07-09 21:15 UTC, Leo9Rdo commented on app/src/main/res/layout/activity_main.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Прости, не обратил внимания, что два раза использую FrameLayout

2024-07-10 03:41 UTC, pzinkevich42innowise approved these changes

2024-07-10 05:58 UTC, AndrewRav approved these changes

2024-07-10 16:03 UTC, merged