BottomNavigation
Leo9Rdo/FinancialWallet pull request #2
Opened 2024-07-10 21:24 UTC by Leo9Rdo

Add: 
-BottomNavigationar

2024-07-12 14:08 UTC, AndrewRav approved these changes

2024-07-12 14:24 UTC, Valentin2508247 requested changes

2024-07-12 14:24 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/MainActivity.kt
> +        replaceFragment(HomeFragment())
а зачем тут replaceFragment() и Fragment транзакции?

2024-07-12 17:00 UTC, Leo9Rdo commented on app/src/main/java/com/example/financewallet/MainActivity.kt
> +        replaceFragment(HomeFragment())
Осталось от старого кода

2024-07-15 07:50 UTC, AlexVLive requested changes

2024-07-15 07:50 UTC, AlexVLive commented on app/src/main/res/layout/fragment_asset_list.xml
> +        android:layout_height="match_parent" />
Нужен атрибут или android:id (чтобы добавить текст позже), или android:text (добавить текст сразу)

2024-07-15 07:50 UTC, AlexVLive commented on app/src/main/res/layout/fragment_portfolio_list.xml
> +        android:layout_height="match_parent" />
Аналогично

2024-07-15 07:50 UTC, AlexVLive commented on app/src/main/res/layout/fragment_settings.xml
> +        android:layout_height="match_parent" />
Аналогично

2024-07-15 07:50 UTC, AlexVLive commented on app/src/main/res/menu/bottom_nav.xml
> +        android:title="Home" />
Все strings лучше сразу выносить в строковые ресурсы

2024-07-15 07:58 UTC, Valentin2508247 approved these changes

2024-07-16 19:27 UTC, pzinkevich42innowise requested changes

2024-07-16 19:27 UTC, pzinkevich42innowise commented on app/build.gradle
> +    implementation libs.androidx.navigation.compose
Compose???

2024-07-16 19:27 UTC, pzinkevich42innowise commented on app/build.gradle
> +    implementation libs.androidx.navigation.dynamic.features.fragment
Dynamic features???

2024-07-16 19:27 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_home.xml
>          android:layout_height="wrap_content"
А Constraint всё ещё нужен на этом экране?

2024-07-16 21:36 UTC, pzinkevich42innowise requested changes

2024-07-16 21:36 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationFragmentKtx" }
Применение удалил, а это можно и оставить, и так сойдёт

Не надо так поступать, надо думать что делаешь

2024-07-22 17:53 UTC, pzinkevich42innowise approved these changes

2024-07-23 14:50 UTC, merged