Feature/domain models
Leo9Rdo/FinancialWallet pull request #3
Opened 2024-07-13 22:32 UTC by AndrewRav

> Добавил модельные классы
> Добавил интерфейсы репозиториев и операций
> Реализовал репозиторий с активами и сделал вывод списка активов через recycler view

Итого, здесь выстроил структуру проекта вместе с бизнес-логикой и с тем, что будет реализовано в будущем. Для наглядности добавил обычный вывод списка активов. Не добавлял здесь Хилт и не делал ВьюМодели, чтобы не перегружать ПР.
![image](https://github.com/user-attachments/assets/1b58e8e4-5f5d-4999-af87-d41ce15d05ba)

2024-07-14 07:38 UTC, Leo9Rdo approved these changes

2024-07-15 09:47 UTC, Valentin2508247 requested changes

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/data/AssetRepositoryImpl.kt
> +    private val assets = StubAssetList.assets.toMutableList()
почему тут mutable а не immutableList?

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/domain/repository/AssetRepository.kt
> +    fun getAllAssets(): List<Asset>
как будто в интерфейсе репозитория не написаны все нужные методы

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/data/StubAssetList.kt
> +    private val usd = Currency("USD", "Доллар", 1.0)
можно через sealed class

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/domain/entity/Currency.kt
> +data class Currency(
можно реализовать как sealed class

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/domain/entity/Settings.kt
> +    var displayCurrency: Currency = Currency("USD", "Доллар", 1.0)
мутабельные переменные в data класс не очень хорошая практика
лучше сделать val
при изменении displayCurrency отправлять новый объект в liveData

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/presentation/assetList/AssetListFragment.kt
> +    private lateinit var assetAdapter: AssetAdapter
давай сделаем без lateinit

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/presentation/assetList/AssetListFragment.kt
> +        binding.assetRecyclerView.layoutManager = LinearLayoutManager(requireContext())
давай сделаем метод configureRecyclerView

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/presentation/assetList/AssetListFragment.kt
> +        val assetRepository: AssetRepository = AssetRepositoryImpl()
в будущем через вьюмодель

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/presentation/rv/AssetAdapter.kt
> +class AssetAdapter : RecyclerView.Adapter<AssetViewHolder>() {
можно сделать через ListAdapter

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/presentation/rv/AssetViewHolder.kt
> +        binding.assetName.text = asset.name
binding.apply

2024-07-15 09:47 UTC, Valentin2508247 commented on app/src/main/res/layout/item_asset.xml
> +        android:text="Asset name"
текст через ресурсы для всех textView

2024-07-17 10:31 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/domain/repository/AssetRepository.kt
> +    fun getAllAssets(): List<Asset>
Временный вариант, ибо уже реализую этот репозиторий. По мере разработки экрана с активами будут добавляться методы

2024-07-17 10:33 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/domain/entity/Settings.kt
> +    var displayCurrency: Currency = Currency("USD", "Доллар", 1.0)
Решил в принципе отказаться от этого класса и делать всё просто через Currency. По итогу понял, что класс Settings избыточный и не используется

2024-07-17 11:01 UTC, Valentin2508247 commented on app/src/main/java/com/example/financewallet/domain/repository/AssetRepository.kt
> +    fun getAllAssets(): List<Asset>
хорошо

2024-07-22 17:51 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/entity/Asset.kt
> +    }
В этом нет смысла. Если посмотреть decompiled kotlin bytecode, то мы увидим, что data классы наследников в автогенерации это не используют, а используют все поля и без вызова super.

Если хочешь где-то вызывать методы equals и hashCode на абстрактном Asset, то эту логику следует переписать

2024-07-22 17:51 UTC, pzinkevich42innowise requested changes
Убрать equals и hashCode для абстрактного класса

2024-07-23 07:59 UTC, Valentin2508247 approved these changes

2024-07-24 09:22 UTC, Valentin2508247 approved these changes

2024-07-24 11:26 UTC, merged