Feature/hilt base setup
Leo9Rdo/FinancialWallet pull request #4
Opened 2024-07-25 14:58 UTC by AndrewRav

> Добавил Hilt
> Переписал вывод Активов на ViewModel и использовал Hilt для di

2024-07-25 17:39 UTC, Leo9Rdo approved these changes

2024-07-26 07:55 UTC, Valentin2508247 requested changes

2024-07-26 07:55 UTC, Valentin2508247 commented on app/build.gradle
> +    id 'kotlin-kapt'
через alias и version catalogs

в .toml файле есть секция [plugins]

2024-07-26 10:43 UTC, Valentin2508247 approved these changes

2024-07-26 11:21 UTC, merged