core portfolio
Leo9Rdo/FinancialWallet pull request #5
Opened 2024-08-03 21:30 UTC by Leo9Rdo

- I converted data request functions to coroutines;
- Сhanged data retrieval methods to use Dispatcher IO;
- Сreated the basic CRUD screen for Portfolio;
- Made minor fixes;
- Updated the layout;
- Added Hilt to the Portfolio screen.

2024-08-04 02:48 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/domain/interactor/PortfolioInteractor.kt
Насколько я понял, WithContext достаточно прописать один раз и желательно на самом нижнем уровне, то есть на уровне репозитория

А тут получается, что ты прописал на уровне ВьюМодели под launch сразу и ещё в Интеракторе. То есть уже выходит избыточно (как минимум, странно выглядит) плюс не на нижнем уровне.

Не уверен, что именно так надо делать, как я описал выше, и никак иначе. Поэтому пока тыкну аппрув, подождём чек и комментарии от ревьверов)

2024-08-05 06:54 UTC, pzinkevich42innowise requested changes

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/interactor/PortfolioInteractor.kt
Всё верно, достаточно только в репозитории. Зачем интерактору знать, что для доступа к данным надо переключить диспатчер?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/build.gradle
> +    }
```suggestion
```

Ну какой датабиндинг? Зачем? Он мёртв и не стоит про него вспоминать

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/PortfolioRepositoryImpl.kt
> +            portfolios[index] = portfolio
Может поменять структуру хранения на map?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/PortfolioRepositoryImpl.kt
> +            throw Exception("Portfolio not found")
А другого типа для ошибки не нашлось?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/PortfolioRepositoryImpl.kt
> +            throw Exception("Portfolio not found")
ресурсы

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +        binding.recyclerViewPortfolios.layoutManager = LinearLayoutManager(context)
Почему не в реусрсах?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +            adapter.notifyDataSetChanged()
Давай это в адаптер перенесём

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +                    (portfolioViewModel.portfolios.value?.size ?: 0),
Может интерактор сам будет заниматься созданием портфеля и назначением ему нового id? Кажется это часть бизнес-логики, несмотря на то, что id - это синтетическое поле

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +            .setNegativeButton("Cancel", null)
ресурсы

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +            .setPositiveButton("Save") { _, _ ->
ресурсы

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +    }
В двух этих диалогах есть что-то общее, давай придумаем один общий метод показа диалога

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +            .setNegativeButton("Cancel", null)
ресурсы

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/portfolio/PortfolioListFragment.kt
> +            .setNegativeButton("No", null)
ресурсы

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/rv/PortfolioDiffCallback.kt
> +        return oldItem.areContentsTheSame(newItem)
почему equals не подошёл?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/rv/PortfolioViewHolder.kt
> +        binding.btnDelete.setOnClickListener { onDelete(portfolio) }
with(binding) { 
...
}

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio_list.xml
> +        android:layout_height="match_parent">
какую роль выполняет Frame?

2024-08-05 06:54 UTC, pzinkevich42innowise commented on app/src/main/res/layout/fragment_portfolio_list.xml
> +            tools:ignore="UselessParent">
С чего это игнор?

2024-08-08 00:23 UTC, pzinkevich42innowise requested changes

2024-08-08 00:23 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/entity/Portfolio.kt
> +    }
Это всё ещё нужно?

2024-08-08 00:23 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/interactor/PortfolioInteractor.kt
> +        val newId = (portfolios.maxByOrNull { it.id }?.id ?: 0) + 1
Это бизнес-логика? Кажется это работа репозитория, разобраться с синтетическим полем для хранения данных

2024-08-12 13:58 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/PortfolioRepositoryImpl.kt
> +    }
не критично:
Мне больше нравится вариант upsert/save. Когда отдаёшь на сохранение, а добавление или сохранение будет неважно. Так и ошибка будет не нужна

2024-08-12 13:59 UTC, pzinkevich42innowise requested changes

2024-08-12 13:59 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/PortfolioRepositoryImpl.kt
> +    override suspend fun getPortfolio(id: Int): Portfolio {
А переключить диспатчер не надо?

2024-08-14 14:46 UTC, pzinkevich42innowise approved these changes

2024-08-14 15:17 UTC, merged