Currency fetch with API
Leo9Rdo/FinancialWallet pull request #6
Opened 2024-08-04 01:31 UTC by AndrewRav

Во время того, как делал экран с валютами, подумал, почему бы сразу не брать валюты с API, как говорится, зачем мелочиться. По итогу, набрался сил и смелости, и начал пробовать, вроде, даже что-то получилось. Правда не уверен, что правильно :)

> Добавил в проект retrofit, moshi и корутины
> Обновил валюты, добавил реализацию репозитория и интерактор
> Сделал NetworkModule, где настроил Retrofit и Moshi, также подружил это всё дело с Хилтом. Добавил таймауты.
> Подготовил всё, что принимать JSON с помощью Moshi
> Сделал спиннер (раскрывающийся список) на экран настроек, куда поместил Валюты
> Добавил SharedPreference, чтобы сохранять выбранную валюту
> Очевидно, использовал корутины (suspend функцию и viewModelScope), чтобы получить валюты с API
> Также пришлось здесь же перевести вывод списка Активов на корутины, так как в заглушке использовал принятую валюту

<img src="https://github.com/user-attachments/assets/c47cd468-f6ce-4606-bd15-d2e4e59a3e87" width="248">

2024-08-04 08:03 UTC, Leo9Rdo approved these changes

2024-08-05 06:40 UTC, pzinkevich42innowise requested changes

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/build.gradle
> +    implementation libs.moshi.kotlin.v1130
Забываем про моши также как и вспомнили, используем kotlinx.serialization

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/AssetRepositoryImpl.kt
> +        return withContext(Dispatchers.IO) {
В этом ПРе получается и перевод на IO, и сеть. Получается 2 задачи на 1 ПР, что очень плохо

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/CurrencyRepositoryImpl.kt
> +    override fun mapToCurrency(apiCurrency: RateResponse): Currency {
А зачем тебе в интерфейсе такой метод? Кажется это внутренний метод и у него не должно быть никакого override

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/CurrencyRepositoryImpl.kt
> +    override suspend fun fetchCurrencies(curId: String, ondate: String?): Currency {
ondate где-то используется?

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/CurrencyApiService.kt
С чего вдруг описание сетевого сервиса стало частью домена?

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/domain/entity/RateResponse.kt
Наличие аннотаций для сериализации также должно было намекнуть на то, что это data слой

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/settings/CurrencyViewModel.kt
> +                currencyRepository.fetchCurrencies("EUR")
Может как-то в другом месте определить список валют? Метод обновления во вью модели не совсем для этого подходит

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/settings/CurrencyViewModel.kt
> +        _selectedCurrencyModel.value = currency.name
Кажется тут надо префы менять

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/settings/SettingsFragment.kt
> +    private fun setupSpinner() {
Поновее и посвежее спиннера с точки зрения дизайна ничего не придумалось?

2024-08-05 06:40 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/presentation/settings/SettingsFragment.kt
> +            val currencyName = availableCurrencies.map { it.name }
Зачем маппить внутри отоюражения данных? Кажется этим VM заниматься должна

2024-08-12 14:05 UTC, pzinkevich42innowise requested changes

2024-08-12 14:05 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
Почему не DataStore? Теперь знаем что это и можем использовать

2024-08-12 14:05 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +moshiKotlinVersion = "1.13.0"
?

2024-08-12 14:05 UTC, pzinkevich42innowise commented on gradle/libs.versions.toml
> +moshi-kotlin-v1130 = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlinVersion" }
?

2024-08-14 20:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")
Форматирование поехало

2024-08-14 20:49 UTC, pzinkevich42innowise requested changes

2024-08-14 20:49 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    override suspend fun saveCurrency(currencyName: String) {
Dispatchers.IO

2024-08-14 20:49 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    override suspend fun getSavedCurrency(): String {
Dispatchers.IO

2024-08-14 21:31 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")
Это кстати окей, если объявление выносить на уровень всего файла, выглядит довольно странно, но так в доке написано. Или можно просто в классе писать и не париться?

2024-08-14 21:42 UTC, AndrewRav commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    override suspend fun getSavedCurrency(): String {
Прописал явно, но всё же. Разве, DataStore сам не переключает на потоки ввода-вывода под капотом? Просто я вот на такую картиночку нашёл, она родом из android codelabs в разделе про DataStore.

![image](https://github.com/user-attachments/assets/a7b0dd73-b2d6-40a8-b794-e990cc587e95)

2024-08-16 20:28 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    override suspend fun getSavedCurrency(): String {
Может и переключает, но я бы для надёжности сам переключил)

2024-08-16 20:28 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/financewallet/data/SettingsRepositoryImpl.kt
> +    private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")
Если применяешь внутри класса - можно и оставить в нём

2024-08-16 20:29 UTC, pzinkevich42innowise approved these changes

2024-08-16 21:09 UTC, merged